header:
  version: 15

machine: iMX8MNano-evk
distro: nxp-custom
target:
  - nxp-custom-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: mickledore
    layers:
      meta:

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    branch: mickledore
    layers: 
      meta-oe:
      meta-python:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    branch: mickledore
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-nxp:
    layers:
      meta-nxp:

  meta-tools:
    layers:
      meta-tools:

local_conf_header:
  meta-nxp: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
