header:
  version: 15

machine: nxp-imx8mn
distro: nxp-custom
target:
  - nxp-custom-image-core

repos:
  poky:
    url: "https://github.com/yoctoproject/poky.git"
    branch: mickledore
    tag: mickledore-4.2.4
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    branch: mickledore
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-multimedia:

  meta-board-nxp:
    layers:
      meta-board-nxp:

bblayers_conf_header:
  standard: |
    # Add custom settings

local_conf_header:
  standard: |
    # NXP EULA agreement
    ACCEPT_FSL_EULA = "1"
    # Additional image features
    USER_CLASSES ?= "buildstats"
    PATCHRESOLVE = "noop"

  packaging: |
    # Switch to Debian packaging
    PACKAGE_CLASSES = "package_deb"
    # Enable PR server to avoid version-going-backward issue
    PRSERV_HOST = "localhost:0"
    
  cleaning: |
    # Remove the old image before the new one generated to save disk space
    RM_OLD_IMAGE = "1"
    # Clean up working directory after build
    INHERIT += "rm_work"

  diskmon: |
    BB_DISKMON_DIRS ??= "\
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K \
      "