header:
  version: 15

machine: nxp-imx8mn
distro: nxp-custom
target:
  - nxp-custom-image-core

repos:
  poky:
    url: "https://github.com/yoctoproject/poky.git"
    branch: kirkstone
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    branch: kirkstone
    layers: 
      meta-oe:
      meta-python:
      meta-multimedia:
      meta-networking:

  meta-imx:
    url: "https://github.com/nxp-imx/meta-imx"
    branch: kirkstone-5.15.71-2.2.2
    layers:
      meta-bsp:
      meta-sdk:

  meta-freescale:
    url: "https://github.com/Freescale/meta-freescale"
    branch: kirkstone
    # layers:
      # Adding the meta-freescale layer itself

  meta-board-nxp:
    layers:
      meta-board-nxp:

bblayers_conf_header:
  standard: |
    # Add custom settings

local_conf_header:
  standard: |
    # NXP EULA agreement
    ACCEPT_FSL_EULA = "1"
    # Additional image features
    USER_CLASSES ?= "buildstats"
    PATCHRESOLVE = "noop"

  packaging: |
    # Switch to Debian packaging and include package-management in the image
    PACKAGE_CLASSES = "package_deb"
    EXTRA_IMAGE_FEATURES += "package-management"
    
  cleaning: |
    # Remove the old image before the new one generated to save disk space
    RM_OLD_IMAGE = "1"
    # Clean up working directory after build
    INHERIT += "rm_work"

  diskmon: |
    BB_DISKMON_DIRS ??= "\
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"