header:
  version: 15

machine: imx8mn-lpddr4-evk
distro: nxp-custom
target:
  - nxp-custom-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: kirkstone
    layers:
      meta:

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    branch: kirkstone
    layers: 
      meta-oe:
      meta-python:
      meta-multimedia:
      meta-networking:

  meta-imx:
    url: "https://github.com/nxp-imx/meta-imx"
    branch: kirkstone-5.15.71-2.2.0
    layers:
      meta-bsp:
      meta-sdk:

  meta-freescale:
    url: "https://github.com/Freescale/meta-freescale"
    branch: kirkstone
    # layers:
      # Adding the meta-freescale layer itself

  meta-freescale-distro:
    url: "https://github.com/Freescale/meta-freescale-distro"
    branch: kirkstone
    # layers:
      # Adding the meta-freescale-distro layer itself

  meta-freescale-3rdparty:
    url: "https://github.com/Freescale/meta-freescale-3rdparty"
    branch: kirkstone
    # layers:
      # Adding the meta-freescale-3rdparty layer itself

  meta-board-nxp:
    layers:
      meta-board-nxp:

local_conf_header:
  meta-board-nxp: |
    # Uncoment the lines below in local.conf
    # 
    # ACCEPT_FSL_EULA = "1"
    #
    # ---------------------- 
    # Some useful lines you may want to copy to your site.conf for development
    # EXTRA_IMAGE_FEATURES = "debug-tweaks dev-pkgs"
    # Switch to Debian packaging and include package-management in the image
    # PACKAGE_CLASSES = "package_deb"
    # EXTRA_IMAGE_FEATURES += "package-management"
    # Remove the old image before the new one generated to save disk space
    # RM_OLD_IMAGE = "1"
    # Clean up working directory after build
    # INHERIT += "rm_work"
    #
    # ----------------------