header:
  version: 15

machine: imx8mn-lpddr4-evk
distro: nxp-custom
target:
  - nxp-custom-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.6"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: kirkstone
    layers:
      meta:

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    branch: kirkstone
    layers: 
      meta-oe:
      meta-python:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    branch: kirkstone
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-imx:
    url: "https://github.com/nxp-imx/meta-imx"
    branch: kirkstone-5.15.32-2.0.0
    layers:
      meta-bsp:
      meta-sdk:

  meta-freescale:
    url: "https://github.com/Freescale/meta-freescale"
    branch: kirkstone
    layers:
      meta-bsp:
      meta-sdk:

  meta-nxp:
    layers:
      meta-nxp:

  meta-tools:
    layers:
      meta-tools:

local_conf_header:
  meta-nxp: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks dev-pkgs"
