MACHINE ??= 'imx8mnevk'
DISTRO ?= 'nxp-custom'
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"
PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
CONF_VERSION = "2"

DL_DIR ?= "${BSPDIR}/downloads/"
ACCEPT_FSL_EULA = "1"

# Switch to RPM packaging and include package-management in the image
PACKAGE_CLASSES = "package_rpm"
EXTRA_IMAGE_FEATURES += "package-management"

# Set timezone area
IMAGE_INSTALL:append =  " tzdata"
DEFAULT_TIMEZONE = "America/Sao_Paulo"

# Remove the old image before the new one generated to save disk space
RM_OLD_IMAGE = "1"
# Clean up working directory after build
INHERIT += "rm_work"

# Image extra size adjusted to 3G
IMAGE_ROOTFS_EXTRA_SPACE = "3145728"
